name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ts-node-express-jest:latest
    - name: Run migrations to set up test db
      run: docker run -i --env NODE_ENV=test ts-node-express-jest:latest npm run migrate
    - name: Run tests
      run: docker run -i --env NODE_ENV=test ts-node-express-jest:latest npm test